### ISSUE TITLE
French for Start for Demo

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/sql-join-table#16]
Démarrer.

Start in french due to end being `fin`. via @gaand

**Comment by gaand** [comment]
Perhaps a better answer is to just use `start` and `stop`?  I've thought of, seen others do this, before, but always seem to forget.  Perhaps recording it here will help me remember to use it this time.

**Comment by gaand** [comment]
Changed to use `start_on` and `end_on` in 37f3344e7f11c05761a2979daea19f31497a9a88
